name: steam_ui
description: UI library inspired by the classic Steam interface from the early 2000s
version: 0.1.0
license: MIT
homepage: https://saitam.dev
repository: https://github.com/solismatias/steam_ui


environment:
  flutter: ">=3.19.0"
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ">=5.1.0 <11.0.0"

topics:
  - ui
  - theme
  - retro
  - steam
  - widgets

issue_tracker: https://github.com/solismatias/steam_ui/issues

screenshots:
  - description: "Steam UI Demo 1"
    path: assets/steam_ui_1.png
  - description: "Steam UI Demo 2"
    path: assets/steam_ui_2.png
  - description: "Steam UI Demo 3"
    path: assets/steam_ui_3.png
