name: steam_ui
description: UI library inspired by the classic Steam interface from the early 2000s
version: 0.1.0+1
license: MIT


environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ">=5.1.0 <11.0.0"
